apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  rules:
  - host: {{ .Values.ingress.prefix }}ada.{{ .Values.environment }}.{{ .Values.ingress.dnsZone }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.name }}
              port:
                number: 80