apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }} 
    environment: {{ .Values.environment }}
data:
  ENVIRONMENT: {{ required "Value 'environment' is required" .Values.environment | quote }}
{{- range $key, $value := .Values.envVariables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}