apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: container-port