spring:
  application:
    name: letscode-by-ada
  profiles: default, local, develop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: "always" 
  datasource:
    url: ""
    username: ""
    password: ""

security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: Y2FiZcOnYSBkYSBvbsOnYQ==